### ISSUE TITLE
Install dependencies in the background

### ISSUE THREAD

**Issue by felix-d1strict** [D1strict/AL-JobTracker#11]
The user should not run another installation routine of Visual C and so on.... Such code dependencies should be installed in the background.

**Comment by AdyStudios** [comment]
Thought: There are batch and vbs scripts to run an application in the background, but thats not gonna work because we wont know if its done installing

**Comment by felix-d1strict** [comment]
> Thought: There are batch and vbs scripts to run an application in the background, but thats not gonna work because we wont know if its done installing

I don't like .bat and .vbs scripts. I have already found something, maybe this will work. Let's see.

**Comment by AdyStudios** [comment]
This is the best I could find for Inno Setup, but it no longer works (probobly because it was designed for windowsXP)
https://www.programmersought.com/article/65391859865/

**Comment by felix-d1strict** [comment]
I have a solution already. But I will not pack the installation routine until all issues regarding 1.1.0 are finished.

**Comment by AdyStudios** [comment]
Okay, cool

**Comment by AdyStudios** [comment]
Well... Last issue remaining

**Comment by felix-d1strict** [comment]
Yes that's right. However, I still want to test if the file hash check works.
Also, I'll probably have to set up the restart of the DRP again, I messed up the RebootDRP_x**.exe somewhere. ;-)
