### ISSUE TITLE
Implement the DRP

### ISSUE THREAD

**Issue by felix-d1strict** [D1strict/AL-JobTracker#12]
We should implement the Discord Rich Presence in the tracker. This way there is no need to install etcars twice and the user is spared another installation routine.
Of course, the whole thing also builds on the dependencies in Issue https://github.com/D1strict/AL-JobTracker/issues/11.

**Comment by AdyStudios** [comment]
The lazyest way to do this would be to only install etcars from the drp.

**Comment by felix-d1strict** [comment]
Then there is again the problem that two installation routines have to be started.
I have thought that I will store the Rich Presence directly in the code. etcars will then be installed in the background (see https://github.com/D1strict/AL-JobTracker/issues/11).

**Comment by AdyStudios** [comment]
Okay, let me try to integrate ALDRP into app.js

**Comment by felix-d1strict** [comment]
I already have done this at home on my computer locally. So you havnt to do this anymore.
When i am back home, i will commit this.

**Comment by felix-d1strict** [comment]
Should be done at this point.
