### ISSUE TITLE
Check for updates - wrong query

### ISSUE THREAD

**Issue by AdyStudios** [D1strict/AL-JobTracker#13]
When pressing the check for updates button on the systray, the "Error: The update check cannot be performed. Try again later." will pop up twice, AFTER that it shows the right notification (tracker is up to date / update avalible)

**Comment by felix-d1strict** [comment]
Yep. But the title of this issue should be improoved. 'cause it isnt a "Fake".

**Comment by felix-d1strict** [comment]
Can you check, if the bugfix is working? I am just on my mobile at work.
@AdyStudios

**Comment by AdyStudios** [comment]
I'll get home soon

**Comment by felix-d1strict** [comment]
I am at home now. So i can test it myself. But thank you anyways.

**Comment by AdyStudios** [comment]
Just arrived now 😆

**Comment by felix-d1strict** [comment]
Yup, this is working.
