### ISSUE TITLE
Creating "jobs" folder

### ISSUE THREAD

**Issue by AdyStudios** [D1strict/AL-JobTracker#16]
I noticed that you used the jobs folder in the script, and that makes an issue for me of course because I don't have the jobs folder. This let me think that we should add a folder creation function. I figured out how to mkdirs but my only issue was that I couldn't inploment it properly. I tried first adding the createdir function to the 
if(err){}, but it didn't waited for the folder to be created. Then I tried using the: try{} catch{} finally{} things, but it didn't worked at all. 
Also couldnt find any solutions on the internet (that actually worked). I'm going to keep trying.

**Comment by felix-d1strict** [comment]
Not a Bug. I will put the jobs-folder into the installer.

**Comment by felix-d1strict** [comment]
And i havnt upload the jobsfolder to github yet.

**Comment by AdyStudios** [comment]
Right, but I thought it would be better to keep the github page clean, but okay, thats a way to do it lmao

**Comment by felix-d1strict** [comment]
Why? One folder more or less 🤷‍♂️
GitHub doesnt need to be "clean". End users will usually not look at the source code anyway.

**Comment by AdyStudios** [comment]
Yeah, okay, okay
