### ISSUE TITLE
Send JSON instead of variables

### ISSUE THREAD

**Issue by felix-d1strict** [D1strict/AL-JobTracker#17]
Instead of sending individual values from etcars to the API, it might be a code optimization if we send the JSON data to the API right away. However, this also requires some modifications to the API.

**Comment by felix-d1strict** [comment]
Of course, this would also make it easier to save and send local jobs. 😉

**Comment by AdyStudios** [comment]
I'm nearly done with this one, but modifications to the Api has to be done (for receving json)

**Comment by AdyStudios** [comment]
Im going to upload tomorrow

**Comment by AdyStudios** [comment]
It was a pain, but as mentioned in the commit notes its, done. Of course (as mentioned before) API has to be modified.

**Comment by felix-d1strict** [comment]
Any ideas? The API is rebuilt, and can receive JSON. I have tested this here: https://reqbin.com/
Only it doesn't seem to work via the tracker. But right now I'm too tired to research it further. Maybe you @AdyStudios  are already awake before me and you can look at this. Because I'm going to sleep now. ;D

```
(node:27624) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object
    at Function.byteLength (buffer.js:515:11)
    at exports.XMLHttpRequest.send (C:\Users\felix\Documents\AL-JobTracker\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:363:80)
    at APISaving (C:\Users\felix\Documents\AL-JobTracker\app.js:466:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
```

**Comment by AdyStudios** [comment]
I will look at it today

**Comment by felix-d1strict** [comment]
I've forgot to stringyfy the JSON Value... 🤦‍♂️

**Comment by AdyStudios** [comment]
Well... xD
