### ISSUE TITLE
dependencies installers still get downloaded regardless of unchecking it in the installer

### ISSUE THREAD

**Issue by AdyStudios** [D1strict/AL-JobTracker#19]
I don't know if this is intended or not, but when unchecking to download dependencies in the installer regardless of that, it still downloads the dependencies installers.

**Comment by felix-d1strict** [comment]
You mean when you select "Without dependencies"?
For me, nothing is downloaded, only files are unpacked.
![depenc](https://user-images.githubusercontent.com/68828301/123545863-8dbe0080-d75a-11eb-8670-f63ba5fb1f7b.png)

**Comment by AdyStudios** [comment]
Sorry I'm stupid, I couldn't see the dropdown, only after that, when it says "Select additional tasks". But I usually don't read through installation files 
![image](https://user-images.githubusercontent.com/74962285/123545880-ac23fc00-d75a-11eb-80f4-069906379035.png)
