### ISSUE TITLE
systray icon error

### ISSUE THREAD

**Issue by doouz** [D1strict/AL-JobTracker#27]
**Describe the bug**
If I change the current path in app.js to the correct path of the systray.ico inside the assets folder, app.js starts but the systray doesn't start correctly. The solution I found was transforming the .ico into base64 (for example, using this website: https://base64.guru/converter/encode/image/ico) and with that it already runs with the icon correctly. 

**To Reproduce**
1. Go to 'app.js' line 625
2. search for "icon:"
3. Put the correct path for the systray.ico
4. Start the app.js with the app_x64.exe

**Expected behavior**
Starts but the systray doesn't start correctly.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.1.0

**Additional context**
This bug don't happen when you start in dev mode from terminal with "node app.js"

**Comment by AdyStudios** [comment]
Thanks, for opening this issue!
The problem with the base64 image is that there will be a huge chunk of charatchers and it will lag out the editor. (I tried it before 1.1.0 when messing with systray). I will see what I can do (•‿•)
We also found this issue.

**Comment by felix-d1strict** [comment]
I mark this error as "wontfix", because this is not an error on our part, but rather the error of node-systray2.

**Comment by felix-d1strict** [comment]
Maybe @OwainYT will find a solution.
An interim solution is currently to set "copyDir" to true.

**Comment by felix-d1strict** [comment]
! This product is no longer supported and has therefore been archived.
