### ISSUE TITLE
When finishing a job, it keeps repeating the sending to the API forever 

### ISSUE THREAD

**Issue by doouz** [D1strict/AL-JobTracker#28]
**Describe the bug**
When finishing a job, it keeps repeating the sending to the API forever.

**To Reproduce**
1. Take fast job
2. Deliver and end the job
3. See error

**Expected behavior**
Keep repeating the sending to the API forever

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.1.0

**Additional context**

**Comment by felix-d1strict** [comment]
Yes, we also have this mistake. We currently solve this on the server side with a query, if job XY already exists, then do not save the job. If job XY does not exist, then save the job. As a work around.

**Comment by doouz** [comment]
I added `apistatus = "false";` on line 486 and it seems that it was fixed, I am doing more tests to confirm

**Comment by doouz** [comment]
> 
> 
> I added `apistatus = "false";` on line 486 and it seems that it was fixed, I am doing more tests to confirm

It was solved for me, I tried several jobs of 5km and 7km and sent at the beginning and then at the end without problem.

**Comment by felix-d1strict** [comment]
Thank you, feel free to create a PR. 🤝🙂

**Comment by felix-d1strict** [comment]
! This product is no longer supported and has therefore been archived.
