### ISSUE TITLE
Save jobs locally

### ISSUE THREAD

**Issue by felix-d1strict** [D1strict/AL-JobTracker#8]
Save jobs locally when not connected to the Internet. And sent them, if there is a connection again.

**Comment by doouz** [comment]
I don't know about nodejs, but reading a bit some basic docs, could it be something like this? 

https://pastebin.com/Je33L6kz (password: **LKcyRP5QRW**)

This can go inside the `} else if (retryCount > 9) {` that way the job is only saved in a file if it is impossible to connect to the API. Perhaps the format in which it is saved can be improved, maybe in JSON and that way on the web simply puts a form for the driver to upload his job file and the web takes care of processing the fields. 

The file is encoded with base64 and on web we just use `base64_decode();` (if you use PHP), just to make it difficult to modify the information.

**Comment by AdyStudios** [comment]
And yes, for this to be completed we have to first finish this one https://github.com/D1strict/AL-JobTracker/issues/17

**Comment by felix-d1strict** [comment]
If no connection to the Internet and the API can be established, jobs are stored locally.
Local jobs are sent to the API with a delay if there is an Internet connection, so that the computer and the API are not overloaded.
